# Generated by Django 2.2.7 on 2020-08-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_auto_20200803_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git',
            name='actual_shipping_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='git',
            name='linkman',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='git',
            name='rdr_reason',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='git',
            name='receiver',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='git',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
