# Generated by Django 2.2.7 on 2020-08-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_auto_20200804_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ipmi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
