# Generated by Django 2.2.7 on 2020-07-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.MaterialMaster', unique=True),
        ),
        migrations.AddField(
            model_name='packserialnumber',
            name='pack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.Pack'),
        ),
        migrations.AddField(
            model_name='packserialnumber',
            name='serialnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.SerialNumber'),
        ),
    ]
