# Generated by Django 2.2.7 on 2020-07-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_auto_20200723_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationroutes',
            name='repaired_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repaired_station', to='line.Station'),
        ),
        migrations.AddField(
            model_name='stationroutes',
            name='station_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
