# Generated by Django 2.2.7 on 2020-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_auto_20200726_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationroutes',
            name='station_type',
        ),
        migrations.AddField(
            model_name='station',
            name='station_type',
            field=models.IntegerField(null=True),
        ),
    ]
