# Generated by Django 2.2.7 on 2020-10-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_auto_20200727_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Version',
            fields=[
                ('prod_version_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('prod_version_description', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('create_date', models.DateField()),
            ],
        ),
    ]
