# Generated by Django 2.2.7 on 2020-10-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0005_prod_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_version',
            name='prod_version_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
