# Generated by Django 2.2.7 on 2020-10-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_auto_20201013_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationroutes',
            name='action_station',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationroutes',
            name='audit_station',
            field=models.IntegerField(default=0),
        ),
    ]
