# Generated by Django 2.2.7 on 2020-10-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0007_auto_20201014_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Version_test',
            fields=[
                ('prod_version_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('prod_version_description', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='model',
        ),
        migrations.AlterField(
            model_name='prod_version',
            name='prod_version_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='route',
            name='prod_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='line.Prod_Version_test'),
        ),
    ]
