# Generated by Django 2.2.7 on 2020-10-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0008_auto_20201030_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_version',
            name='prod_version_description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='prod_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='line.Prod_Version'),
        ),
        migrations.DeleteModel(
            name='Prod_Version_test',
        ),
    ]
