# Generated by Django 2.2.7 on 2020-11-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0009_auto_20201030_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_version',
            name='prod_version_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prod_version',
            name='prod_version_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='prod_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line.Prod_Version', unique=True),
        ),
    ]
