# Generated by Django 2.2.7 on 2020-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='updater',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='rework',
            field=models.IntegerField(null=True),
        ),
    ]
