# Generated by Django 2.2.7 on 2020-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_auto_20200724_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='assy_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='generated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='pack_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='ship_date',
            field=models.DateTimeField(null=True),
        ),
    ]
