# Generated by Django 2.2.7 on 2020-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_auto_20200724_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairgroup',
            name='replacement',
            field=models.IntegerField(choices=[(0, 'NOT A REPLACEMENT'), (1, 'REPLACEMENT')], default=0, help_text='Is replacement'),
        ),
        migrations.AlterField(
            model_name='repairdetail',
            name='replacement',
            field=models.IntegerField(choices=[(0, 'NOT REPLACED'), (1, 'REPLACED')], help_text='replaced'),
        ),
    ]
