# Generated by Django 2.2.7 on 2020-07-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_auto_20200726_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmaster',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='pallet_limit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='repairmain',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.SerialNumber'),
        ),
        migrations.AlterField(
            model_name='testingresult',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.SerialNumber'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='skuno',
            field=models.ForeignKey(db_column='skuno', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.MaterialMaster'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.WoStatusCategory'),
        ),
        migrations.AlterField(
            model_name='workorderdetail',
            name='model_id',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.MaterialMaster'),
        ),
        migrations.AlterField(
            model_name='workorderdetail',
            name='workorder_id',
            field=models.ForeignKey(db_column='workorder_id', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.WorkOrder'),
        ),
    ]
