# Generated by Django 2.2.7 on 2020-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_auto_20200726_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumberlog',
            name='log_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
