# Generated by Django 2.2.7 on 2020-09-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_auto_20200813_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlApp',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('control_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Value Name')),
                ('control_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Control Description')),
                ('control_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Control Value')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('updater', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updater')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='SerializationRule',
            fields=[
                ('rule_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rule Type')),
                ('rule_length', models.IntegerField()),
                ('start_sequence', models.IntegerField()),
                ('current_sequence', models.IntegerField()),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('updater', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updater')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='SerializationRuleValues',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('value_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Value Name')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Value')),
                ('rule_length', models.IntegerField()),
                ('start_sequence', models.IntegerField()),
                ('current_sequence', models.IntegerField()),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('updater', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updater')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
                ('rule_id', models.ForeignKey(db_column='rule_id', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.SerializationRule')),
            ],
        ),
    ]
