# Generated by Django 2.2.7 on 2020-09-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_controlapp_serializationrule_serializationrulevalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='sn_status_category',
            field=models.ForeignKey(db_column='sn_status_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.SN_Status_Category'),
        ),
    ]
