# Generated by Django 2.2.7 on 2020-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_auto_20200923_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumberlog',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serialnumberlog',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serialnumberlog',
            name='sn_status_category',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
