# Generated by Django 2.2.7 on 2020-10-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_auto_20201013_1350'),
        ('manufacturing', '0011_auto_20201002_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='production_version',
            field=models.ForeignKey(db_column='production_version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='line.Prod_Version'),
        ),
    ]
