# Generated by Django 2.2.7 on 2020-07-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phantomassy',
            old_name='phantom_genereated_sn',
            new_name='phantom_generated_sn',
        ),
    ]
