# Generated by Django 2.2.7 on 2020-07-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_group', models.CharField(max_length=255)),
                ('scan_type', models.CharField(default='CSERIALNO', max_length=30)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.Route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line.Station')),
            ],
            options={
                'unique_together': {('station', 'route', 'material_group')},
            },
        ),
    ]
