"""
Django settings for sfc project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r+6a&9#gn3(*rk-vtz^_(!#fx%k^b_8e_qy+@ttw$kkh9=5wj2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'manufacturing',
    'bootstrap_modal_forms',
    'widget_tweaks',
    'maskconfig',
    'line',
    'rules',
    'rest_framework',
    'offline_station',
    'shipping',
    'crispy_forms',
    'git',
    'qms',
    'wms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # During development only
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sfc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': ['django.templatetags.static']
        },
    },
]

WSGI_APPLICATION = 'sfc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases





DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'cims_wi_uat',
    #     'USER': 'postgres',
    #     'PASSWORD': '!PYMSdb001@',
    #     'HOST': '10.20.199.57',
    #      'PORT': '5432',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'mydb3',
    #     'USER': 'postgres',
    #     'PASSWORD': '!PYMSdb001@',
    #     'HOST': '10.20.199.55',
    #      'PORT': '5433',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'test-changes',
    #     'USER': 'postgres',
    #     'PASSWORD': '!PYMSdb001@',
    #     'HOST': '10.20.199.55',
    #      'PORT': '5433',
    # }
    #  'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'mydb1',
    #     'USER': 'postgres',
    #     'PASSWORD': '!PYMSdb001@',
    #     'HOST': '10.20.199.55',
    #      'PORT': '5432',
    # }

############ for Sui ###################################
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'IMS',
    #     'USER': 'postgres',
    #     'PASSWORD': 'foxconnit',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #      # 'NAME': 'shipping_integration',
    #     #'NAME': 'shipping_test_1',
    #     'NAME' : 'combined_shipping',
    #     'USER': 'postgres',
    #     'PASSWORD': '!PYMSdb001@',
    #     'HOST': '10.20.199.55',
    #     'PORT': '5432',
    # }
        'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Foxconn1!',
        'HOST': '127.0.0.1',
         'PORT': '5432',
    }

#############################################
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #      # 'NAME': 'shipping_integration',
    #     #'NAME': 'shipping_test_1',
    #     'NAME' : 'combined_shipping',
    #     'USER': 'postgres',
    #     'PASSWORD': '!PYMSdb001@',
    #     'HOST': '10.20.199.55',
    #     'PORT': '5432',
    # }

#############################################
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'mydb3',
    #     'USER': 'postgres',
    #     'PASSWORD': 'root',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'mydb13',
    #     'USER': 'postgres',
    #     'PASSWORD': 'foxconnit',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'mydb3',
    #     'USER': 'postgres',
    #     'PASSWORD': '!PYMSdb001@',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'new_db',
    #     'USER': 'postgres',
    #     'PASSWORD': 'root',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    #
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "live-static","static-root")

STATICFILES_DIRS = (
  os.path.join(BASE_DIR, 'static'),
  '/usr/local/lib/python3.6/site-packages/django/contrib/admin/static',
)
# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/manufacturing/'

APPEND_SLASH=False
AUTH_PROFILE_MODULE = 'manufacturing.Profile'     # app name (dot) model name


# ###### email##############

#transactional email services: SendGrid, MailGun, Mandrill.
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = '' # mail service smtp
# EMAIL_HOST_USER = '' # email id
# EMAIL_HOST_PASSWORD = '' #password
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
