# Generated by Django 2.2.7 on 2020-07-23 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('mask_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=20, verbose_name='Creator')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
                ('updater', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updater')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.MaterialMaster')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=200)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('data_type', models.CharField(choices=[('Hard Code', 'Hard Code'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year'), ('Numeric', 'Numeric'), ('Alpha Numeric', 'Alpha Numeric'), ('Text', 'Text'), ('Model', 'Model')], help_text='Type of data segment', max_length=20)),
                ('length', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('value', models.CharField(blank=True, max_length=15, null=True)),
                ('creator', models.CharField(max_length=20, verbose_name='Creator')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
                ('updater', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updater')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
                ('mask_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maskconfig.Mask')),
            ],
        ),
    ]
