# Generated by Django 2.2.7 on 2020-07-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maskconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='mask_id',
            field=models.ForeignKey(db_column='mask_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='maskconfig.Mask'),
        ),
    ]
