# Generated by Django 2.2.7 on 2020-11-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0012_workorder_production_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_BS_INSPEC_AQL_VALUE',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('aql_value', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_BS_INSPEC_LEVEL',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inspection_level', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_BS_INSPEC_PARAMETERS',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inspect_parameters', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_BS_INSPECTION_TOOL',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inspection_tool', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_IQC_INSPECTION',
            fields=[
                ('inspection_form_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('inspection_operator_id', models.CharField(max_length=255)),
                ('inspection_method', models.CharField(max_length=255)),
                ('inspection_standard', models.CharField(max_length=255)),
                ('inspection_result', models.CharField(max_length=255)),
                ('inspection_aql_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.TB_BS_INSPEC_AQL_VALUE')),
                ('inspection_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.TB_BS_INSPEC_LEVEL')),
                ('inspection_parameters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.TB_BS_INSPEC_PARAMETERS')),
                ('inspection_tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.TB_BS_INSPECTION_TOOL')),
            ],
        ),
        migrations.CreateModel(
            name='TB_MANUFACTURE_DATA',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('manufacture_name', models.CharField(max_length=255)),
                ('manufacture_number', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TB_MRB',
            fields=[
                ('mrb_form_no', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('mrb_result', models.CharField(max_length=255)),
                ('select_numbers', models.CharField(max_length=255)),
                ('select_person', models.CharField(max_length=255)),
                ('select_date', models.DateField()),
                ('audit_person', models.CharField(max_length=255)),
                ('audit_date', models.DateField()),
                ('inspection_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms.TB_IQC_INSPECTION')),
            ],
        ),
        migrations.CreateModel(
            name='TB_MATERIAL_INSPECTION_FREE_LIST',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('material_hh_part_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.MaterialMaster')),
                ('material_manufacture_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.TB_MANUFACTURE_DATA')),
            ],
        ),
        migrations.AddField(
            model_name='tb_iqc_inspection',
            name='is_inspection_free',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms.TB_MATERIAL_INSPECTION_FREE_LIST'),
        ),
        migrations.AddField(
            model_name='tb_iqc_inspection',
            name='material_hh_part_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.MaterialMaster'),
        ),
    ]
