# Generated by Django 2.2.7 on 2020-11-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_bs_inspec_level',
            name='inspection_level',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tb_bs_inspec_parameters',
            name='inspect_parameters',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tb_bs_inspection_tool',
            name='inspection_tool',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tb_material_inspection_free_list',
            name='material_hh_part_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.MaterialMaster', unique=True),
        ),
    ]
