# Generated by Django 2.2.7 on 2020-11-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_auto_20201116_1006'),
        ('qms', '0002_auto_20201112_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_INCOMING_IQC_LIST',
            fields=[
                ('inspection_form_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('inspected', models.IntegerField(blank=True, choices=[(0, 'Not Inspected'), (1, 'Inspected')], default='Not Inspected', help_text='Inspected', null=True)),
                ('material_qty', models.IntegerField(blank=True, default=0)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('material_hh_part_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.MaterialMaster')),
            ],
        ),
    ]
