# Generated by Django 2.2.7 on 2020-12-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0013_auto_20201116_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='receiving_form',
            fields=[
                ('receiving_form_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('po_no', models.CharField(blank=True, max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('receiving_form_status', models.CharField(blank=True, choices=[(0, 'Not Finished'), (1, 'Finished')], default='Not Finished', max_length=255, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=255)),
                ('creator', models.CharField(max_length=255, verbose_name='Creator')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('updater', models.CharField(blank=True, max_length=100, null=True, verbose_name='Updater')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='receiving_form_detail',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('po', models.CharField(blank=True, max_length=255)),
                ('received_qty', models.IntegerField(blank=True, default=0)),
                ('target_qty', models.IntegerField(blank=True, default=0)),
                ('to_iqc_qty', models.IntegerField(blank=True, default=0)),
                ('gr_qty', models.IntegerField(blank=True, default=0)),
                ('receiving_status', models.CharField(blank=True, choices=[(0, 'Not Received'), (1, 'Received')], default='Not Received', help_text='Received', max_length=255, null=True)),
                ('material_hh_part_no', models.ForeignKey(db_column='skuno_id', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.MaterialMaster')),
                ('receiving_form_id', models.ForeignKey(db_column='receiving_form_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.receiving_form')),
            ],
        ),
    ]
