# Generated by Django 2.2.7 on 2020-12-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving_form',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='receiving_form',
            old_name='supplier',
            new_name='supplier_id',
        ),
        migrations.RenameField(
            model_name='receiving_form_detail',
            old_name='po',
            new_name='po_no',
        ),
        migrations.AddField(
            model_name='receiving_form_detail',
            name='line_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receiving_form',
            name='creator',
            field=models.CharField(max_length=255, null=True, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='receiving_form',
            name='receiving_form_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Finished'), (1, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='receiving_form_detail',
            name='receiving_form_id',
            field=models.ForeignKey(db_column='receiving_form_id', on_delete=django.db.models.deletion.CASCADE, to='wms.receiving_form'),
        ),
        migrations.AlterField(
            model_name='receiving_form_detail',
            name='receiving_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Received'), (1, 'Received')], default=0, help_text='Received'),
        ),
    ]
