# Generated by Django 2.2.7 on 2020-12-07 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_auto_20201116_1006'),
        ('qms', '0004_auto_20201207_2320'),
        ('wms', '0002_auto_20201201_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving_form_detail',
            old_name='material_hh_part_no',
            new_name='model_id',
        ),
        migrations.RemoveField(
            model_name='receiving_form_detail',
            name='gr_qty',
        ),
        migrations.RemoveField(
            model_name='receiving_form_detail',
            name='po_no',
        ),
        migrations.CreateModel(
            name='gr_document_no',
            fields=[
                ('row_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('po_no', models.CharField(max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, default=0)),
                ('document_no_rtu', models.CharField(max_length=255, null=True)),
                ('inspection_form_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qms.iqc_inspection')),
                ('model_id', models.ForeignKey(db_column='skuno_id', on_delete=django.db.models.deletion.CASCADE, to='manufacturing.MaterialMaster')),
            ],
        ),
    ]
