# Generated by Django 2.2.7 on 2020-08-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynumberdetail',
            name='skuno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.MaterialMaster'),
        ),
    ]
