# Generated by Django 2.2.7 on 2020-08-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20200807_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='deliverynumberdetail',
            name='deliverynumber_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipping.DeliveryNumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverynumberdetail',
            name='salesorder_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shipping.SalesOrder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pallet',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='completed',
            field=models.IntegerField(blank=True, choices=[(0, 'Not completed'), (1, 'Completed')], help_text='completed', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed Date'),
        ),
        migrations.AlterField(
            model_name='deliverynumberdetail',
            name='current_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deliverynumberdetail',
            name='request_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deliverynumberdetail',
            name='ship_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='full',
            field=models.IntegerField(blank=True, choices=[(0, 'NOT FULL'), (1, 'FULL')], help_text='full', null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='full_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Full Date'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='pallet_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (0, 'closed')], default=1, help_text='status'),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='updater',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pallet',
            name='wh_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='palletserialnumber',
            name='updater',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ship_cancelled',
            field=models.IntegerField(blank=True, choices=[(0, 'Not cancelled'), (1, 'Cancelled')], help_text='cancel', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ship_hold',
            field=models.IntegerField(blank=True, choices=[(0, 'Not hold'), (1, 'Hold')], help_text='hold', null=True),
        ),
    ]
